runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  
  APP_LOG: errorlog
  STORAGE_DIR: /tmp
  APP_KEY: base64:icfMCnbFlVe6vi4pLyO44h53DJJuaOWIoxihuq5Gq/0=
  DB_DATABASE: tmhexpress
  APP_DEBUG: false
  DB_PORT: 3306
  DB_CONNECTION: mysql
  DB_USERNAME: root
  DB_PASSWORD: i1rK9xumy6w5Ov5i
  DB_SOCKET: "/cloudsql/tmhexpress:us-central1:tmhexpress2022"

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.sparkpostmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: 
  MAIL_PASSWORD: 

beta_settings:
  cloud_sql_instances: "tmhexpress:us-central1:tmhexpress2022"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5